export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_PRODUCT_PRICE_TO_CART: "ADD_PRODUCT_PRICE_TO_CART",
  ADD_TO_CART: "ADD_TO_CART",
  SHOW_CART: "SHOW_CART",
  REMOVE_FROM_CART : "REMOVE_FROM_CART",
  SHOW_CART_TOTAL_AMOUNT : "SHOW_CART_TOTAL_AMOUNT"
};
